# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.market_openapi_api import MarketOpenapiApi  # noqa: E501
from openapi_client.rest import ApiException


class TestMarketOpenapiApi(unittest.TestCase):
    """MarketOpenapiApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.market_openapi_api.MarketOpenapiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bindable_markets(self):
        """Test case for bindable_markets

        可绑定的商店列表  # noqa: E501
        """
        pass

    def test_create_app(self):
        """Test case for create_app

        应用列表  # noqa: E501
        """
        pass

    def test_create_app_version(self):
        """Test case for create_app_version

        创建应用版本  # noqa: E501
        """
        pass

    def test_get_app_hub_info(self):
        """Test case for get_app_hub_info

        获取镜像仓库信息  # noqa: E501
        """
        pass

    def test_get_market_info(self):
        """Test case for get_market_info

        获取商店信息  # noqa: E501
        """
        pass

    def test_get_orgs(self):
        """Test case for get_orgs

        获取组织机构(行业)列表  # noqa: E501
        """
        pass

    def test_get_user_app_detail(self):
        """Test case for get_user_app_detail

        应用详情  # noqa: E501
        """
        pass

    def test_get_user_app_list(self):
        """Test case for get_user_app_list

        应用列表  # noqa: E501
        """
        pass

    def test_get_user_app_version_detail(self):
        """Test case for get_user_app_version_detail

        应用版本信息  # noqa: E501
        """
        pass

    def test_get_user_app_versions(self):
        """Test case for get_user_app_versions

        应用版本列表  # noqa: E501
        """
        pass

    def test_update_app(self):
        """Test case for update_app

        更新应用信息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
