# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v1alpha1_ingress_sream_route import V1alpha1IngressSreamRoute  # noqa: E501
from openapi_client.rest import ApiException

class TestV1alpha1IngressSreamRoute(unittest.TestCase):
    """V1alpha1IngressSreamRoute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1IngressSreamRoute
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v1alpha1_ingress_sream_route.V1alpha1IngressSreamRoute()  # noqa: E501
        if include_optional :
            return V1alpha1IngressSreamRoute(
                component_key = '0', 
                connection_timeout = 56, 
                port = 56, 
                protocol = '0'
            )
        else :
            return V1alpha1IngressSreamRoute(
                component_key = '0',
                connection_timeout = 56,
                port = 56,
                protocol = '0',
        )

    def testV1alpha1IngressSreamRoute(self):
        """Test V1alpha1IngressSreamRoute"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
