# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v1_app_version_detail_response import V1AppVersionDetailResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestV1AppVersionDetailResponse(unittest.TestCase):
    """V1AppVersionDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1AppVersionDetailResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v1_app_version_detail_response.V1AppVersionDetailResponse()  # noqa: E501
        if include_optional :
            return V1AppVersionDetailResponse(
                app_key_id = '0', 
                app_name = '0', 
                create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                delivery_mode = '0', 
                description = '0', 
                enable = True, 
                is_plugin = True, 
                market_id = '0', 
                rainbond_version = '0', 
                template = '0', 
                template_type = '0', 
                update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                update_version = 56, 
                version = '0', 
                version_alias = '0'
            )
        else :
            return V1AppVersionDetailResponse(
                app_key_id = '0',
                app_name = '0',
                create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                delivery_mode = '0',
                description = '0',
                enable = True,
                is_plugin = True,
                market_id = '0',
                rainbond_version = '0',
                template = '0',
                template_type = '0',
                update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                update_version = 56,
                version = '0',
                version_alias = '0',
        )

    def testV1AppVersionDetailResponse(self):
        """Test V1AppVersionDetailResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
