# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v1alpha1_ingress_http_route import V1alpha1IngressHTTPRoute  # noqa: E501
from openapi_client.rest import ApiException

class TestV1alpha1IngressHTTPRoute(unittest.TestCase):
    """V1alpha1IngressHTTPRoute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1IngressHTTPRoute
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v1alpha1_ingress_http_route.V1alpha1IngressHTTPRoute()  # noqa: E501
        if include_optional :
            return V1alpha1IngressHTTPRoute(
                component_key = '0', 
                connection_timeout = 56, 
                cookies = {
                    'key' : '0'
                    }, 
                default_domain = True, 
                headers = {
                    'key' : '0'
                    }, 
                load_balancing = '0', 
                location = '0', 
                port = 56, 
                proxy_buffer = True, 
                proxy_buffer_numbers = 56, 
                proxy_buffer_size = 56, 
                proxy_header = {
                    'key' : '0'
                    }, 
                request_body_size_limit = 56, 
                request_timeout = 56, 
                response_timeout = 56, 
                ssl = True, 
                websocket = True
            )
        else :
            return V1alpha1IngressHTTPRoute(
                component_key = '0',
                connection_timeout = 56,
                cookies = {
                    'key' : '0'
                    },
                default_domain = True,
                headers = {
                    'key' : '0'
                    },
                load_balancing = '0',
                location = '0',
                port = 56,
                proxy_buffer = True,
                proxy_buffer_numbers = 56,
                proxy_buffer_size = 56,
                proxy_header = {
                    'key' : '0'
                    },
                request_body_size_limit = 56,
                request_timeout = 56,
                response_timeout = 56,
                ssl = True,
                websocket = True,
        )

    def testV1alpha1IngressHTTPRoute(self):
        """Test V1alpha1IngressHTTPRoute"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
