# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V1AppClassifications(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'app_classification_id': 'str',
        'app_classification_name': 'str',
        'parent_app_classification_id': 'str'
    }

    attribute_map = {
        'app_classification_id': 'appClassificationID',
        'app_classification_name': 'appClassificationName',
        'parent_app_classification_id': 'parentAppClassificationID'
    }

    def __init__(self, app_classification_id=None, app_classification_name=None, parent_app_classification_id=None, local_vars_configuration=None):  # noqa: E501
        """V1AppClassifications - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._app_classification_id = None
        self._app_classification_name = None
        self._parent_app_classification_id = None
        self.discriminator = None

        self.app_classification_id = app_classification_id
        self.app_classification_name = app_classification_name
        self.parent_app_classification_id = parent_app_classification_id

    @property
    def app_classification_id(self):
        """Gets the app_classification_id of this V1AppClassifications.  # noqa: E501

        应用分类 ID  # noqa: E501

        :return: The app_classification_id of this V1AppClassifications.  # noqa: E501
        :rtype: str
        """
        return self._app_classification_id

    @app_classification_id.setter
    def app_classification_id(self, app_classification_id):
        """Sets the app_classification_id of this V1AppClassifications.

        应用分类 ID  # noqa: E501

        :param app_classification_id: The app_classification_id of this V1AppClassifications.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and app_classification_id is None:  # noqa: E501
            raise ValueError("Invalid value for `app_classification_id`, must not be `None`")  # noqa: E501

        self._app_classification_id = app_classification_id

    @property
    def app_classification_name(self):
        """Gets the app_classification_name of this V1AppClassifications.  # noqa: E501

        分类名称  # noqa: E501

        :return: The app_classification_name of this V1AppClassifications.  # noqa: E501
        :rtype: str
        """
        return self._app_classification_name

    @app_classification_name.setter
    def app_classification_name(self, app_classification_name):
        """Sets the app_classification_name of this V1AppClassifications.

        分类名称  # noqa: E501

        :param app_classification_name: The app_classification_name of this V1AppClassifications.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and app_classification_name is None:  # noqa: E501
            raise ValueError("Invalid value for `app_classification_name`, must not be `None`")  # noqa: E501

        self._app_classification_name = app_classification_name

    @property
    def parent_app_classification_id(self):
        """Gets the parent_app_classification_id of this V1AppClassifications.  # noqa: E501

        父级分类 ID  # noqa: E501

        :return: The parent_app_classification_id of this V1AppClassifications.  # noqa: E501
        :rtype: str
        """
        return self._parent_app_classification_id

    @parent_app_classification_id.setter
    def parent_app_classification_id(self, parent_app_classification_id):
        """Sets the parent_app_classification_id of this V1AppClassifications.

        父级分类 ID  # noqa: E501

        :param parent_app_classification_id: The parent_app_classification_id of this V1AppClassifications.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and parent_app_classification_id is None:  # noqa: E501
            raise ValueError("Invalid value for `parent_app_classification_id`, must not be `None`")  # noqa: E501

        self._parent_app_classification_id = parent_app_classification_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AppClassifications):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1AppClassifications):
            return True

        return self.to_dict() != other.to_dict()
